theme: jekyll-theme-minimal
title: [Food Security and Resilience Copernicus Hackathon]
description: [Training documentation for the Food Security and Resilience Copernicus Hackathon, held at the University of Leicester]
show_downloads: ["true"]
